#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

#server:
#  port: 9090 #DEFAULT PORT: 8761

#spring:
#  application:
#    name: app-discovery-server
  #config:
  #  import:
  #  - optional:configserver:http://localhost:8888/
#  cloud:
#    config:
#      uri: http://localhost:8888/
#      username: admin
#      password: 123456